#!/bin/bash

. parse-args "$@"

set -ex

PROJECT_DIR=/opt/dev/repo/infrastructure/docker/${SERVICE}/${CONTEXT}
CONTEXT=${CONTEXT-gex}

docker --context "$CONTEXT" compose --project-directory "$PROJECT_DIR" pull
docker --context "$CONTEXT" compose --project-directory "$PROJECT_DIR" up --detach
docker --context "$CONTEXT" compose --project-directory "$PROJECT_DIR" logs --follow