#!/bin/bash

# Requires user to be a sudoer: `usermod -aG sudo <username>`
# curl --location https://fmtr.link/dev/init | bash

set -ex

USERNAME=${USERNAME-$(whoami)}

sudo mkdir -p /opt/dev/ve /rs
sudo chown ${USERNAME}:${USERNAME} -R /opt/dev

sudo apt update --yes
sudo apt install python3-venv --yes
python3 -m venv /opt/dev/ve/shell

/opt/dev/ve/shell/bin/pip install corio
sudo ln -s /opt/dev/ve/shell/bin/run-script /rs/s

sudo /rs/s set-user-sudo --username=$USERNAME
sudo /rs/s set-secure-path

echo "source /rs/s" >> ~/.bashrc

