#!/bin/bash

. parse-args "$@"

set -ex

PORT=${PORT:-/dev/ttyUSB0}
CHIP=${CHIP:-auto}
BAUD=${BAUD:-460800}

esptool --port $PORT flash-id
esptool --chip $CHIP --port $PORT --baud $BAUD erase-flash
esptool --chip $CHIP --port $PORT --baud $BAUD write-flash --flash-mode dout --flash-size detect 0x0 "$FILE"

tasmota-terminal --port=$PORT